import '../../../../export.dart';
import '../../../../view/bottom_nav/home/ziarat/map.dart';
import '../../../../view/bottom_nav/home/ziarat/page.dart';

final ziaratProvider = ChangeNotifierProvider.autoDispose<ZiaratNotifier>((ref) => ZiaratNotifier());

class ZiaratNotifier extends ChangeNotifier {
  BuildContext? _context;
  BuildContext get context => _context!;
  set context(BuildContext value) => _context = value;

  WidgetRef? _ref;
  WidgetRef get ref => _ref!;
  set ref(WidgetRef value) => _ref = value;

  ZiaratCities? selectedCity;
  List<ZiaratModel> ziarats = [];
  List<ZiaratModel> selectedZiarat = [];
  List<ZiaratModel> sortedZiarats = [];
  StreamSubscription<Position>? positionStream;
  bool isLoading = false;
  bool isGeneratingAutoZiarats = true;
  String myCurrentLocation = '';
  ZiaratDestinationsCreationOptions? selectedDestinationsCreationOption;
  UserModel? user;

  initialization() async {
    try {
      user = await LocalStorageManager.getUser();
      myCurrentLocation = await Helper.getLocation(context);
      checkAlreadyDoingZiarat();
      if (context.mounted) notifyListeners();
    } catch (e) {
      if (kDebugMode) log(e.toString());
      errorToast(e.toString());
    }
  }

  void checkAlreadyDoingZiarat() async {
    var query = await historyCollection
        .where(Filter.and(Filter('user_id', isEqualTo: user!.uid), Filter('type', isEqualTo: UserActivityType.ziarat.name), Filter('is_completed', isEqualTo: false)))
        .get()
        .timeout(const Duration(seconds: Helper.timeOutTime), onTimeout: () => throw Helper.timeoutError);
    if (query.docs.isNotEmpty) {
      var result = await showGeneralDialog(context: context, pageBuilder: (context, animation, secondaryAnimation) => AlreadyDialog(isDoingUmra: false));
      if (result == true) Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) => ZiaratMapPage()));
    }
  }

  void updateSelectedCity(ZiaratCities city) {
    selectedCity = city;
    notifyListeners();
  }

  void updateSelectedDestinationsCreationOption(ZiaratDestinationsCreationOptions option) {
    selectedDestinationsCreationOption = option;
    notifyListeners();
  }

  reset() {
    selectedCity = null;
    selectedDestinationsCreationOption = null;
    positionStream?.cancel();
    selectedZiarat.clear();
    sortedZiarats.clear();
    isLoading = false;
    notifyListeners();
  }

  void goBackToSelectCity() {
    Navigator.pop(context);
    reset();
    checkAlreadyDoingZiarat();
  }

  void goToBackFromAutoSelectionPage() {
    Navigator.pop(context);
    positionStream?.cancel();
    notifyListeners();
  }

  void goToDestinationGenerationPage() {
    selectedDestinationsCreationOption = null;
    positionStream?.cancel();
    notifyListeners();
    Navigator.push(context, MaterialPageRoute(builder: (context) => ChooseDestinations()));
  }

  updateSelectedZiarat(ZiaratModel ziarat) {
    if (selectedZiarat.contains(ziarat)) {
      selectedZiarat.remove(ziarat);
    } else {
      selectedZiarat.add(ziarat);
    }
    notifyListeners();
  }

  void generateZiarat() async {
    try {
      isLoading = true;
      notifyListeners();
      var doc = await settingsCollection.doc(CommonDoc.ziarat.name).get().timeout(const Duration(seconds: Helper.timeOutTime), onTimeout: () => throw Helper.timeoutError);
      ziarats = List.from(doc.data()![selectedCity?.name]).map<ZiaratModel>((map) => ZiaratModel.fromMap(map)).toList();
      if (ziarats.isNotEmpty) {
        ziarats = ziarats.sublist(0, Helper.userSubscription?.plan.type != PlanType.free.name ? null : 3);
      }
      if (selectedDestinationsCreationOption == ZiaratDestinationsCreationOptions.manual) {
        selectedZiarat.clear();
        isLoading = false;
        notifyListeners();
        await Navigator.push(context, MaterialPageRoute(builder: (context) => ManualSelection()));
      } else {
        Navigator.push(context, MaterialPageRoute(builder: (context) => AutoGeneratedZiaratPlan()));
      }
    } catch (e) {
      if (kDebugMode) log(e.toString());
      if (context.mounted) errorToast(e.toString());
    } finally {
      isLoading = false;
      notifyListeners();
    }
  }

  Future<void> getDistance() async {
    try {
      sortedZiarats.clear();
      isGeneratingAutoZiarats = true;
      if (context.mounted) notifyListeners();
      var position = await Geolocator.getCurrentPosition();
      sortedZiarats =
          ziarats.map<ZiaratModel>((ziarat) {
            var distance = Geolocator.distanceBetween(position.latitude, position.longitude, ziarat.lat.toDouble(), ziarat.lng.toDouble());
            return ziarat.copyWith(distance: (distance / 1000).toStringAsFixed(0));
          }).toList();
      sortedZiarats.sort((a, b) => int.parse(a.distance).compareTo(int.parse(b.distance)));
      if (context.mounted) notifyListeners();
      positionStream = Geolocator.getPositionStream(locationSettings: LocationSettings(accuracy: LocationAccuracy.bestForNavigation)).listen((position) async {
        if (!context.mounted) return positionStream?.cancel();
        sortedZiarats =
            ziarats.map<ZiaratModel>((ziarat) {
              var distance = Geolocator.distanceBetween(position.latitude, position.longitude, ziarat.lat.toDouble(), ziarat.lng.toDouble());
              return ziarat.copyWith(distance: (distance / 1000).toStringAsFixed(0));
            }).toList();
        sortedZiarats.sort((a, b) => int.parse(a.distance).compareTo(int.parse(b.distance)));
        if (context.mounted) notifyListeners();
      });
    } catch (e) {
      if (kDebugMode) log(e.toString());
      if (context.mounted) errorToast(e.toString());
    }
    isGeneratingAutoZiarats = false;
    if (context.mounted) notifyListeners();
  }

  void createZiaratRoute() async {
    isLoading = true;
    notifyListeners();
    var ziarats = selectedDestinationsCreationOption == ZiaratDestinationsCreationOptions.auto ? sortedZiarats : selectedZiarat;
    var doc = historyCollection.doc();
    var ziaratHistory = ZiaratHistoryModel(
      uid: doc.id,
      isCompleted: false,
      userId: user!.uid,
      total: ziarats.length,
      ziaratCity: selectedCity!.name,
      type: UserActivityType.ziarat.name,
      remainingZiarats: ziarats,
      completedZiarats: [],
    );
    await doc.set(ziaratHistory.toMap(createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()));
    isLoading = false;
    notifyListeners();
    if (selectedDestinationsCreationOption == ZiaratDestinationsCreationOptions.manual) {
      Navigator.pop(context);
    } else {
      goToBackFromAutoSelectionPage();
    }
    await Navigator.push(context, MaterialPageRoute(builder: (context) => ZiaratMapPage(ziaratHistory: ziaratHistory)));
    selectedZiarat.clear();
    notifyListeners();
  }

  @override
  void dispose() {
    positionStream?.cancel();
    super.dispose();
  }
}
