part of 'page.dart';

class AutoGeneratedZiaraatPlan extends ConsumerStatefulWidget {
  const AutoGeneratedZiaraatPlan({super.key});
  @override
  ConsumerState<ConsumerStatefulWidget> createState() => _AutoGeneratedZiaraatPlanState();
}

class _AutoGeneratedZiaraatPlanState extends ConsumerState<AutoGeneratedZiaraatPlan> {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      ref.read(ziaraatProvider.notifier).getDistance();
    });
  }

  @override
  Widget build(BuildContext context) {
    var provider = ref.watch(ziaraatProvider);
    return Background(
      showEmblem: false,
      backgroundType: BackgroundType.logo,
      margin: context.edgeInsets(top: 64, left: 16, right: 16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(padding: context.edgeInsets(top: 16, bottom: 8), child: Text('${LocaleKeys.your_current_location.tr()}:', style: CTextStyle.w500(fontSize: 22))),
          Text(provider.myCurrentLocation, style: CTextStyle.w500(fontSize: 14, color: CColors.deepTeal)),
          Padding(padding: context.edgeInsets(top: 16, bottom: 8), child: Text(LocaleKeys.your_ziaraat_destinations.tr(), style: CTextStyle.w500(fontSize: 20))),
          Expanded(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                provider.isGeneratingAutoZiaraats
                    ? Loading()
                    : provider.sortedZiaraats.isEmpty
                    ? Center(child: Text(LocaleKeys.ziaraat_not_found.tr(), style: CTextStyle.w500(fontSize: 22), textAlign: TextAlign.center))
                    : Expanded(
                      child: ListView.builder(
                        shrinkWrap: true,
                        itemCount: provider.sortedZiaraats.length,
                        itemBuilder: (context, index) {
                          var ziaraat = provider.sortedZiaraats[index];
                          return CMarker(title: isLTR(context) ? ziaraat.title_en : ziaraat.title_ur, distance: ziaraat.distance);
                        },
                      ),
                    ),
                if (!(provider.user?.is_premium ?? false)) CButton(isLoading: provider.isLoading, onTap: provider.onLoadMoreTap, margin: context.edgeInsets(top: 32), title: LocaleKeys.load_more.tr()),
              ],
            ),
          ),
          Padding(
            padding: context.edgeInsets(top: 16, bottom: 64),
            child: Row(
              children: [
                CButton(width: 120, onTap: provider.goToBackFromAutoSelectionPage, title: LocaleKeys.go_back.tr(), backgroundColor: CColors.secondaryBackground, borderColor: CColors.primary, titleColor: CColors.primary, useTitleWidth: true),
                Spacer(),
                if (provider.sortedZiaraats.isNotEmpty) CButton(isLoading: provider.isLoading, onTap: provider.createZiaraatRoute, title: LocaleKeys.start_your_ziaraat.tr()),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
