// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByVmQwpwmvQtkxf4XrUSOEC-bdVsRfRaA',
    appId: '1:626725934618:android:8cd57734cf04650a1ee3a3',
    messagingSenderId: '626725934618',
    projectId: 'umrati-app',
    storageBucket: 'umrati-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7eKVQhjSoIk0Vxj0lxDure8Wsob_6r-8',
    appId: '1:626725934618:ios:f9afdd2b87c73f4a1ee3a3',
    messagingSenderId: '626725934618',
    projectId: 'umrati-app',
    storageBucket: 'umrati-app.firebasestorage.app',
    androidClientId: '626725934618-72imitaqjng30ejvko6fmaoi8bi6ee6h.apps.googleusercontent.com',
    iosClientId: '626725934618-hl7i1o41jtjn3iuachid56gd4ubpeuli.apps.googleusercontent.com',
    iosBundleId: 'com.umrati.umrah.guide.app',
  );

}