part of 'page.dart';

class AutoGeneratedZiaratPlan extends ConsumerStatefulWidget {
  const AutoGeneratedZiaratPlan({super.key});
  @override
  ConsumerState<ConsumerStatefulWidget> createState() => _AutoGeneratedZiaratPlanState();
}

class _AutoGeneratedZiaratPlanState extends ConsumerState<AutoGeneratedZiaratPlan> {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      ref.read(ziaratProvider.notifier).getDistance();
    });
  }

  @override
  Widget build(BuildContext context) {
    var provider = ref.watch(ziaratProvider);
    return Background(
      showEmblem: false,
      backgroundType: BackgroundType.logo,
      logoAlign: Alignment.centerLeft,
      margin: EdgeInsets.only(top: kToolbarHeight * 0.5, left: screenSize.width * 0.06, right: screenSize.width * 0.06, bottom: 85),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(padding: const EdgeInsets.only(top: 16), child: Text('${LocaleKeys.your_current_location.tr()}:', style: CTextStyle.w500(fontSize: 22))),
          Text(provider.myCurrentLocation, style: CTextStyle.w500(fontSize: 14, color: CColors.deepTeal)),
          Padding(padding: const EdgeInsets.only(top: 16), child: Text(LocaleKeys.your_ziarat_destinations.tr(), style: CTextStyle.w500(fontSize: 20))),
          Expanded(
            child:
                provider.isGeneratingAutoZiarats
                    ? Loading()
                    : ListView.builder(
                      itemCount: provider.sortedZiarats.length,
                      itemBuilder: (context, index) {
                        var ziarat = provider.sortedZiarats[index];
                        return CMarker(title: languageDirection(context) == TextDirection.ltr ? ziarat.title_en : ziarat.title_ur, distance: ziarat.distance);
                      },
                    ),
          ),
          Padding(
            padding: const EdgeInsets.only(bottom: 32),
            child: Row(
              children: [
                CButton(
                  onTap: provider.goToBackFromAutoSelectionPage,
                  title: LocaleKeys.go_back.tr(),
                  backgroundColor: Colors.transparent,
                  borderColor: CColors.primary,
                  titleColor: CColors.primary,
                  shadows: [],
                ),
                Spacer(),
                CButton(isLoading: provider.isLoading, onTap: provider.createZiaratRoute, title: LocaleKeys.start_your_ziarat.tr()),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
