part of 'page.dart';

class AutoGeneratedZiaratPlan extends ConsumerStatefulWidget {
  const AutoGeneratedZiaratPlan({super.key});
  @override
  ConsumerState<ConsumerStatefulWidget> createState() => _AutoGeneratedZiaratPlanState();
}

class _AutoGeneratedZiaratPlanState extends ConsumerState<AutoGeneratedZiaratPlan> {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      ref.read(ziaratProvider.notifier).getDistance();
    });
  }

  @override
  Widget build(BuildContext context) {
    var provider = ref.watch(ziaratProvider);
    return Background(
      showEmblem: false,
      backgroundType: BackgroundType.logo,
      logoAlign: Alignment.centerLeft,
      margin: SizeConfig.only(top: kToolbarHeight * 0.5),
      child: Padding(
        padding: SizeConfig.symmetric(horizontal: 16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Padding(padding: SizeConfig.only(top: 16, bottom: 8), child: Text('${LocaleKeys.your_current_location.tr()}:', style: CTextStyle.w500(fontSize: 22))),
            Text(provider.myCurrentLocation, style: CTextStyle.w500(fontSize: 14, color: CColors.deepTeal)),
            Padding(padding: SizeConfig.only(top: 16, bottom: 8), child: Text(LocaleKeys.your_ziarat_destinations.tr(), style: CTextStyle.w500(fontSize: 20))),
            Expanded(
              child:
                  provider.isGeneratingAutoZiarats
                      ? Loading()
                      : ListView.builder(
                        itemCount: provider.sortedZiarats.length,
                        itemBuilder: (context, index) {
                          var ziarat = provider.sortedZiarats[index];
                          return CMarker(title: isLTR(context) ? ziarat.title_en : ziarat.title_ur, distance: ziarat.distance);
                        },
                      ),
            ),
            Padding(
              padding: SizeConfig.only(bottom: SizeConfig.screenHeight * 0.05),
              child: Row(
                children: [
                  CButton(
                    onTap: provider.goToBackFromAutoSelectionPage,
                    title: LocaleKeys.go_back.tr(),
                    backgroundColor: Colors.transparent,
                    borderColor: CColors.primary,
                    titleColor: CColors.primary,
                    shadows: [],
                  ),
                  Spacer(),
                  CButton(isLoading: provider.isLoading, onTap: provider.createZiaratRoute, title: LocaleKeys.start_your_ziarat.tr(), width: SizeConfig.w(150)),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
