import '../../../../export.dart';
import '../../../../view/bottom_nav/home/ziaraat/map.dart';
import '../../../../view/bottom_nav/home/ziaraat/page.dart';
import '../../../../view/subscription/page.dart';

final ziaraatProvider = ChangeNotifierProvider.autoDispose<ZiaraatNotifier>((ref) => ZiaraatNotifier());

class ZiaraatNotifier extends ChangeNotifier {
  BuildContext? _context;
  BuildContext get context => _context!;
  set context(BuildContext value) => _context = value;

  WidgetRef? _ref;
  WidgetRef get ref => _ref!;
  set ref(WidgetRef value) => _ref = value;

  ZiaraatCities? selectedCity;
  List<ZiaraatModel> ziaraats = [];
  List<ZiaraatModel> selectedZiaraat = [];
  List<ZiaraatModel> sortedZiaraats = [];
  StreamSubscription<Position>? positionStream;
  bool isLoading = false;
  bool isGeneratingAutoZiaraats = true;
  String myCurrentLocation = '';
  ZiaraatDestinationsCreationOptions? selectedDestinationsCreationOption;
  UserModel? user;

  initialization() async {
    try {
      user = await LocalStorageManager.getUser();
      myCurrentLocation = await Helper.getLocation(context);
      checkAlreadyDoingZiaraat();
      if (context.mounted) notifyListeners();
    } catch (e) {
      appLog(e.toString());
      errorToast(LocaleKeys.some_thing_went_wrong.tr());
    }
  }

  void checkAlreadyDoingZiaraat() async {
    var query = await historyCollection
        .where(Filter.and(Filter('user_id', isEqualTo: user!.uid), Filter('type', isEqualTo: UserActivityType.ziaraat.name), Filter('is_completed', isEqualTo: false)))
        .get()
        .timeout(const Duration(seconds: Helper.timeOutTime), onTimeout: () => throw Helper.timeoutError);
    if (query.docs.isNotEmpty) {
      var result = await showGeneralDialog(context: context, pageBuilder: (context, animation, secondaryAnimation) => AlreadyDialog(isDoingUmrah: false));
      if (result == true) Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) => ZiaraatMapPage()));
    }
  }

  void updateSelectedCity(ZiaraatCities city) {
    selectedCity = city;
    notifyListeners();
  }

  void updateSelectedDestinationsCreationOption(ZiaraatDestinationsCreationOptions option) {
    selectedDestinationsCreationOption = option;
    notifyListeners();
  }

  reset() {
    selectedCity = null;
    selectedDestinationsCreationOption = null;
    positionStream?.cancel();
    selectedZiaraat.clear();
    sortedZiaraats.clear();
    isLoading = false;
    notifyListeners();
  }

  void goBackToSelectCity() {
    Navigator.pop(context);
    reset();
    checkAlreadyDoingZiaraat();
  }

  void goToBackFromAutoSelectionPage() {
    Navigator.pop(context);
    positionStream?.cancel();
    notifyListeners();
  }

  void goToDestinationGenerationPage() {
    selectedDestinationsCreationOption = null;
    positionStream?.cancel();
    notifyListeners();
    Navigator.push(context, MaterialPageRoute(builder: (context) => ChooseDestinations()));
  }

  updateSelectedZiaraat(ZiaraatModel ziaraat) {
    if (selectedZiaraat.contains(ziaraat)) {
      selectedZiaraat.remove(ziaraat);
    } else {
      selectedZiaraat.add(ziaraat);
    }
    notifyListeners();
  }

  void generateZiaraat() async {
    try {
      isLoading = true;
      notifyListeners();
      var doc = await settingsCollection.doc(CommonDoc.ziaraat.name).get().timeout(const Duration(seconds: Helper.timeOutTime), onTimeout: () => throw Helper.timeoutError);
      ziaraats = List.from(doc.data()![selectedCity?.name]).map<ZiaraatModel>((map) => ZiaraatModel.fromMap(map)).toList();
      if (ziaraats.isNotEmpty) {
        ziaraats = ziaraats.sublist(0, Helper.userSubscription == null ? 3 : null);
      }
      if (selectedDestinationsCreationOption == ZiaraatDestinationsCreationOptions.manual) {
        selectedZiaraat.clear();
        isLoading = false;
        notifyListeners();
        await Navigator.push(context, MaterialPageRoute(builder: (context) => ManualSelection()));
      } else {
        Navigator.push(context, MaterialPageRoute(builder: (context) => AutoGeneratedZiaraatPlan()));
      }
    } catch (e) {
      appLog(e.toString());
      errorToast(LocaleKeys.some_thing_went_wrong.tr());
    } finally {
      isLoading = false;
      notifyListeners();
    }
  }

  Future<void> getDistance() async {
    try {
      sortedZiaraats.clear();
      isGeneratingAutoZiaraats = true;
      if (context.mounted) notifyListeners();
      var position = await Geolocator.getCurrentPosition();
      sortedZiaraats =
          ziaraats.map<ZiaraatModel>((ziaraat) {
            var distance = Geolocator.distanceBetween(position.latitude, position.longitude, ziaraat.lat.toDouble(), ziaraat.lng.toDouble());
            return ziaraat.copyWith(distance: (distance / 1000).toStringAsFixed(0));
          }).toList();
      sortedZiaraats.sort((a, b) => int.parse(a.distance).compareTo(int.parse(b.distance)));
      if (context.mounted) notifyListeners();
      positionStream = Geolocator.getPositionStream(locationSettings: LocationSettings(accuracy: LocationAccuracy.bestForNavigation)).listen((position) async {
        if (!context.mounted) return positionStream?.cancel();
        sortedZiaraats =
            ziaraats.map<ZiaraatModel>((ziaraat) {
              var distance = Geolocator.distanceBetween(position.latitude, position.longitude, ziaraat.lat.toDouble(), ziaraat.lng.toDouble());
              return ziaraat.copyWith(distance: (distance / 1000).toStringAsFixed(0));
            }).toList();
        sortedZiaraats.sort((a, b) => int.parse(a.distance).compareTo(int.parse(b.distance)));
        if (context.mounted) notifyListeners();
      });
    } catch (e) {
      appLog(e.toString());
      errorToast(LocaleKeys.some_thing_went_wrong.tr());
    }
    isGeneratingAutoZiaraats = false;
    if (context.mounted) notifyListeners();
  }

  void onLoadMoreTap() async {
    await Navigator.push(context, MaterialPageRoute(builder: (context) => const SubscriptionPlansPage(isRenewingPlan: true)));
  }

  void createZiaraatRoute() async {
    isLoading = true;
    notifyListeners();
    var ziaraats = selectedDestinationsCreationOption == ZiaraatDestinationsCreationOptions.auto ? sortedZiaraats : selectedZiaraat;
    var doc = historyCollection.doc();
    var ziaraatHistory = ZiaraatHistoryModel(uid: doc.id, isCompleted: false, userId: user!.uid, total: ziaraats.length, ziaraatCity: selectedCity!.name, type: UserActivityType.ziaraat.name, remainingZiaraats: ziaraats, completedZiaraats: []);
    await doc.set(ziaraatHistory.toMap(createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()));
    isLoading = false;
    notifyListeners();
    if (selectedDestinationsCreationOption == ZiaraatDestinationsCreationOptions.manual) {
      Navigator.pop(context);
    } else {
      goToBackFromAutoSelectionPage();
    }
    await Navigator.push(context, MaterialPageRoute(builder: (context) => ZiaraatMapPage(ziaraatHistory: ziaraatHistory)));
    selectedZiaraat.clear();
    notifyListeners();
  }

  @override
  void dispose() {
    positionStream?.cancel();
    super.dispose();
  }
}
