import '../../../export.dart';
import '../../../view/nav/home/ziarat/map.dart';
import '../../../view/nav/home/ziarat/page.dart';

final ziaratProvider = ChangeNotifierProvider.autoDispose<ZiaratNotifier>((ref) => ZiaratNotifier());

class ZiaratNotifier extends ChangeNotifier {
  ZiaratCities? selectedCity;
  WidgetRef? _ref;
  BuildContext? _context;
  get context => _context!;
  List<ZiaratModel> selectedZiarat = [];
  List<ZiaratModel> ziarats = [];
  List<ZiaratModel> sortedZiarats = [];
  StreamSubscription<Position>? positionStream;
  bool isLoading = false;

  String myCurrentLocation = '';

  //* Creating Class Level Variables
  bool showChooseDestinationsPage = false;
  ZiaratDestinationsCreationOptions? selectedDestinationsCreationOption;

  //* Auto Generated Ziarat Class Level Variables
  bool showAutoGeneratedZiaratPlanPage = false;

  UserModel? user;
  bool canPop = false;

  initialization(BuildContext context, WidgetRef ref) async {
    _ref = ref;
    _context = context;
    try {
      user = await LocalStorageManager.getUser();
      checkAlreadyDoingZiarat();
      myCurrentLocation = await getLocation();
      if (context.mounted) notifyListeners();
    } catch (e) {
      if (kDebugMode) log(e.toString());
      errorToast(e.toString());
    }
  }

  void checkAlreadyDoingZiarat() async {
    var doc = await userCollection.doc(user!.uid).get().timeout(const Duration(seconds: Helper.timeOutTime), onTimeout: () => throw Helper.timeoutError);
    var firebaseZiarats = doc.data()!.containsKey(CommonField.selectedZiarat.name) ? doc.data()![CommonField.selectedZiarat.name] : [];
    selectedZiarat = List.from(firebaseZiarats).map((e) => ZiaratModel.fromMap(e)).toList();
    if (selectedZiarat.isNotEmpty) {
      var result = await showGeneralDialog(context: context, pageBuilder: (context, animation, secondaryAnimation) => AlreadyDialog(isDoingUmra: false));
      if (result == true) {
        Navigator.push(context, MaterialPageRoute(builder: (context) => ZiaratMapPage()));
      } else if (result == false || result == null) {
        await userCollection.doc(user!.uid).set({CommonField.selectedZiarat.name: []}, SetOptions(merge: true));
        selectedZiarat.clear();
      }
    }
  }

  void updateSelectedCity(ZiaratCities city) {
    selectedCity = city;
    notifyListeners();
  }

  void updateSelectedDestinationsCreationOption(ZiaratDestinationsCreationOptions option) {
    selectedDestinationsCreationOption = option;
    notifyListeners();
  }

  reset() {
    selectedCity = null;
    selectedDestinationsCreationOption = null;
    positionStream?.cancel();
    selectedZiarat.clear();
    sortedZiarats.clear();
    isLoading = false;
    notifyListeners();
  }

  void goBackToSelectCity() {
    showChooseDestinationsPage = false;
    reset();
    checkAlreadyDoingZiarat();
  }

  void goToBackFromAutoSelectionPage() {
    _ref?.read(bottomNavProvider.notifier).updateLogoAlign(Alignment.center);
    showAutoGeneratedZiaratPlanPage = false;
    positionStream?.cancel();
    notifyListeners();
  }

  void goToDestinationGenerationPage() {
    showChooseDestinationsPage = true;
    selectedDestinationsCreationOption = null;
    positionStream?.cancel();
    notifyListeners();
  }

  updateSelectedZiarat(ZiaratModel ziarat) {
    if (selectedZiarat.contains(ziarat)) {
      selectedZiarat.remove(ziarat);
    } else {
      selectedZiarat.add(ziarat);
    }
    notifyListeners();
  }

  void generateZiarat(BuildContext context) async {
    try {
      isLoading = true;
      notifyListeners();
      var doc = await settingsCollection.doc(CommonDoc.ziarat.name).get().timeout(const Duration(seconds: Helper.timeOutTime), onTimeout: () => throw Helper.timeoutError);
      ziarats = List.from(doc.data()![selectedCity?.name]).map<ZiaratModel>((map) => ZiaratModel.fromMap(map)).toList();

      if (ziarats.isNotEmpty) {
        ziarats = ziarats.sublist(0, Helper.userSubscription?.plan.type != PlanType.free.name ? null : 3);
      }
      if (selectedDestinationsCreationOption == ZiaratDestinationsCreationOptions.manual) {
        selectedZiarat.clear();
        isLoading = false;
        notifyListeners();
        await Navigator.push(context, MaterialPageRoute(builder: (context) => ManualSelection()));
      } else {
        _ref?.read(bottomNavProvider.notifier).updateLogoAlign(Alignment.centerLeft);
        showAutoGeneratedZiaratPlanPage = true;
      }
    } catch (e) {
      if (kDebugMode) log(e.toString());
      if (context.mounted) errorToast(e.toString());
    } finally {
      isLoading = false;
      notifyListeners();
    }
  }

  Future<String> getLocation() async {
    try {
      var position = await Geolocator.getCurrentPosition().timeout(const Duration(seconds: Helper.timeOutTime), onTimeout: () => throw Helper.timeoutError);
      Placemark placemarks = (await placemarkFromCoordinates(position.latitude, position.longitude)).first;
      return '${placemarks.street}, ${placemarks.subLocality}, ${placemarks.locality}, ${placemarks.administrativeArea}';
    } catch (e) {
      if (kDebugMode) log(e.toString());
      if (context.mounted) errorToast(e.toString());
      return '';
    }
  }

  Future<void> getDistance() async {
    try {
      positionStream = Geolocator.getPositionStream(locationSettings: LocationSettings(accuracy: LocationAccuracy.bestForNavigation)).listen((position) async {
        if (!context.mounted) return positionStream?.cancel();
        sortedZiarats =
            ziarats.map<ZiaratModel>((ziarat) {
              var distance = Geolocator.distanceBetween(position.latitude, position.longitude, ziarat.lat.toDouble(), ziarat.lng.toDouble());
              return ziarat.copyWith(distance: (distance / 1000).toStringAsFixed(0));
            }).toList();
        sortedZiarats.sort((a, b) => int.parse(a.distance).compareTo(int.parse(b.distance)));
        notifyListeners();
      });
    } catch (e) {
      if (kDebugMode) log(e.toString());
      if (context.mounted) errorToast(e.toString());
    }
  }

  void createZiaratRoute(BuildContext context) async {
    isLoading = true;
    notifyListeners();
    var user = await LocalStorageManager.getUser();
    await userCollection.doc(user!.uid).set({
      CommonField.selectedZiarat.name: (selectedDestinationsCreationOption == ZiaratDestinationsCreationOptions.auto ? sortedZiarats : selectedZiarat).map((e) => e.toMap()).toList(),
    }, SetOptions(merge: true));
    isLoading = false;
    notifyListeners();
    if (selectedDestinationsCreationOption == ZiaratDestinationsCreationOptions.manual) {
      Navigator.pop(context);
    } else {
      goToBackFromAutoSelectionPage();
    }
    await Navigator.push(context, MaterialPageRoute(builder: (context) => ZiaratMapPage()));
    selectedZiarat.clear();
    notifyListeners();
  }

  void onPopInvokedWithResult(bool didPop, result) {
    if (showAutoGeneratedZiaratPlanPage) {
      goToBackFromAutoSelectionPage();
    } else if (showChooseDestinationsPage) {
      goBackToSelectCity();
    } else {}
  }

  @override
  void dispose() {
    positionStream?.cancel();
    super.dispose();
  }
}
